[package]
name = "az-serial"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Cross-platform serial port communication utilities"

[dependencies]
anyhow.workspace = true
automod.workspace = true
az-derive-aliases.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
tokio.workspace = true

[lints]
workspace = true
