[package]
name = "az-toml"
description = "Gradle 风格 Version Catalog TOML 文件的解析、构建、序列化与合并工具库。"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
az-derive-aliases.workspace = true
serde.workspace = true
thiserror.workspace = true
toml_edit.workspace = true

[dev-dependencies]
tempfile.workspace = true
