use crate::http::HttpClient;
use crate::{KiroAuthSupportError, KiroAuthSupportResult, KiroOidcConfig};
use az_derive_aliases::{
    apply, plain_clone_debug, plain_eq, plain_partial_eq, plain_partial_eq_display,
    serde_eq_default, serde_eq_default_copy, serde_partial_eq_default, serialize_eq,
};
use serde_json::Value;
use std::collections::HashMap;
use std::sync::{Arc, Mutex};
use std::thread::{self, JoinHandle};
use std::time::{Duration, Instant};
use uuid::Uuid;

const PERSONAL_START_URL: &str = "https://view.awsapps.com/start";
const SOCIAL_START_URL: &str = "https://view.awsapps.com/start";
const ENTERPRISE_FALLBACK_START_URL: &str = "https://d-906600eb6f.awsapps.com/start";
const DEVICE_CODE_GRANT_TYPE: &str = "urn:ietf:params:oauth:grant-type:device_code";
const DEFAULT_SCOPES: &[&str] = &[
    "codewhisperer:completions",
    "codewhisperer:analysis",
    "codewhisperer:conversations",
];

/// Kiro login flavor used to select the AWS Builder ID start URL.
#[apply(serde_eq_default_copy)]
pub enum KiroLoginType {
    /// Personal AWS Builder ID.
    #[default]
    Personal,
    /// Social AWS Builder ID path.
    Social,
    /// Enterprise Identity Center start URL.
    Enterprise,
}

impl KiroLoginType {
    /// Resolves the start URL sent to the OIDC registration and device endpoints.
    #[must_use]
    pub fn resolve_start_url(self, enterprise_start_url: Option<&str>) -> String {
        match self {
            Self::Personal => PERSONAL_START_URL.to_owned(),
            Self::Social => SOCIAL_START_URL.to_owned(),
            Self::Enterprise => enterprise_start_url
                .map(str::trim)
                .filter(|url| url.starts_with("https://"))
                .map(|url| url.trim_end_matches('/').to_owned())
                .unwrap_or_else(|| ENTERPRISE_FALLBACK_START_URL.to_owned()),
        }
    }
}

/// Registered OIDC public client returned by `/client/register`.
#[apply(serde_eq_default)]
#[serde(rename_all = "camelCase")]
pub struct KiroClientRegistration {
    #[serde(default)]
    pub client_id: String,
    #[serde(default)]
    pub client_secret: String,
    #[serde(default)]
    pub client_id_issued_at: Option<i64>,
    #[serde(default)]
    pub client_secret_expires_at: Option<i64>,
    #[serde(default)]
    pub authorization_endpoint: Option<String>,
    #[serde(default)]
    pub token_endpoint: Option<String>,
}

/// Device authorization metadata returned by `/device_authorization`.
#[apply(serde_eq_default)]
#[serde(rename_all = "camelCase")]
pub struct KiroDeviceAuthorization {
    #[serde(default)]
    pub device_code: String,
    #[serde(default)]
    pub user_code: String,
    #[serde(default)]
    pub verification_uri: String,
    #[serde(default)]
    pub verification_uri_complete: String,
    #[serde(default)]
    pub expires_in: Option<u64>,
    #[serde(default)]
    pub interval: Option<u64>,
}

impl KiroDeviceAuthorization {
    /// Returns the best URL for a browser to open during user authorization.
    #[must_use]
    pub fn browser_verification_url(&self) -> &str {
        if self.verification_uri_complete.trim().is_empty() {
            &self.verification_uri
        } else {
            &self.verification_uri_complete
        }
    }
}

/// Access token response returned by `/token`, including error responses.
#[apply(serde_partial_eq_default)]
#[serde(rename_all = "camelCase")]
pub struct KiroTokenResponse {
    #[serde(default)]
    pub access_token: Option<String>,
    #[serde(default)]
    pub refresh_token: Option<String>,
    #[serde(default)]
    pub id_token: Option<String>,
    #[serde(default)]
    pub token_type: Option<String>,
    #[serde(default)]
    pub expires_in: Option<u64>,
    #[serde(default)]
    pub error: Option<String>,
    #[serde(default)]
    pub error_description: Option<String>,
    #[serde(flatten)]
    pub extra: serde_json::Map<String, Value>,
}

impl KiroTokenResponse {
    /// Returns true when the response contains an access token.
    #[must_use]
    pub fn is_success(&self) -> bool {
        self.access_token
            .as_deref()
            .is_some_and(|token| !token.trim().is_empty())
    }
}

/// Full device-flow session material needed for later polling.
#[apply(plain_eq)]
pub struct KiroDeviceFlow {
    /// Local UUID generated by this crate.
    pub uuid: String,
    /// Login type used for this flow.
    pub login_type: KiroLoginType,
    /// Resolved AWS Builder ID start URL.
    pub start_url: String,
    /// Registered OIDC client material.
    pub client: KiroClientRegistration,
    /// Device authorization material.
    pub authorization: KiroDeviceAuthorization,
    /// Initial poll interval.
    pub poll_interval: Duration,
}

impl KiroDeviceFlow {
    /// Returns the URL the user should open to approve the device flow.
    #[must_use]
    pub fn verification_url(&self) -> &str {
        self.authorization.browser_verification_url()
    }

    /// Returns the user code shown by the provider, if any.
    #[must_use]
    pub fn user_code(&self) -> &str {
        &self.authorization.user_code
    }
}

/// One poll result from the device-token endpoint.
#[apply(plain_partial_eq)]
pub enum KiroTokenPoll {
    /// User authorization is still pending.
    Pending,
    /// Server requested slower polling.
    SlowDown {
        /// Next interval the caller should use.
        next_interval: Duration,
    },
    /// Device code expired or local polling timed out.
    Expired {
        /// Human-readable reason.
        message: String,
    },
    /// Provider returned an unexpected OAuth error.
    Error {
        /// Human-readable reason.
        message: String,
        /// Raw token response.
        response: KiroTokenResponse,
    },
    /// Token exchange completed.
    Success(KiroTokenResponse),
}

impl KiroTokenPoll {
    /// Returns true for success, expired, or error states.
    #[must_use]
    pub const fn is_terminal(&self) -> bool {
        matches!(
            self,
            Self::Success(_) | Self::Expired { .. } | Self::Error { .. }
        )
    }
}

/// Blocking Kiro device-flow client.
#[apply(plain_clone_debug)]
pub struct KiroDeviceFlowClient {
    config: KiroOidcConfig,
    http: HttpClient,
}

impl KiroDeviceFlowClient {
    /// Creates a client from validated configuration.
    pub fn new(config: KiroOidcConfig) -> KiroAuthSupportResult<Self> {
        config.validate()?;
        Ok(Self {
            http: HttpClient::new(&config)?,
            config,
        })
    }

    /// Creates a client with default AWS OIDC endpoint and polling options.
    pub fn default_client() -> KiroAuthSupportResult<Self> {
        Self::new(KiroOidcConfig::default())
    }

    /// Registers a public OIDC client for a Kiro/AWS Builder ID start URL.
    pub fn register_client(
        &self,
        start_url: impl AsRef<str>,
    ) -> KiroAuthSupportResult<KiroClientRegistration> {
        let body = RegisterClientRequest {
            client_name: self.config.client_name.clone(),
            client_type: "public".to_owned(),
            issuer_url: start_url.as_ref().to_owned(),
            scopes: DEFAULT_SCOPES
                .iter()
                .map(|scope| (*scope).to_owned())
                .collect(),
        };
        let response = self.http.post("/client/register")?.json(&body).send()?;
        let registration: KiroClientRegistration = HttpClient::read_json(response)?;
        if registration.client_id.trim().is_empty() {
            return Err(KiroAuthSupportError::InvalidResponse(
                "register client response missing clientId".to_owned(),
            ));
        }
        Ok(registration)
    }

    /// Starts device authorization for a registered OIDC client.
    pub fn start_device_authorization(
        &self,
        client: &KiroClientRegistration,
        start_url: impl AsRef<str>,
    ) -> KiroAuthSupportResult<KiroDeviceAuthorization> {
        let body = DeviceAuthorizationRequest {
            client_id: client.client_id.clone(),
            client_secret: client.client_secret.clone(),
            start_url: start_url.as_ref().to_owned(),
        };
        let response = self
            .http
            .post("/device_authorization")?
            .json(&body)
            .send()?;
        let authorization: KiroDeviceAuthorization = HttpClient::read_json(response)?;
        if authorization.browser_verification_url().trim().is_empty() {
            return Err(KiroAuthSupportError::InvalidResponse(
                "device authorization response missing verification URI".to_owned(),
            ));
        }
        if authorization.device_code.trim().is_empty() {
            return Err(KiroAuthSupportError::InvalidResponse(
                "device authorization response missing deviceCode".to_owned(),
            ));
        }
        Ok(authorization)
    }

    /// Creates a full device flow for a login type.
    pub fn begin_device_flow(
        &self,
        login_type: KiroLoginType,
        enterprise_start_url: Option<&str>,
    ) -> KiroAuthSupportResult<KiroDeviceFlow> {
        let start_url = login_type.resolve_start_url(enterprise_start_url);
        let client = self.register_client(&start_url)?;
        let authorization = self.start_device_authorization(&client, &start_url)?;
        let provider_interval = authorization.interval.unwrap_or_default();
        let poll_interval = self
            .config
            .poll_interval
            .max(Duration::from_secs(provider_interval));
        Ok(KiroDeviceFlow {
            uuid: Uuid::new_v4().to_string(),
            login_type,
            start_url,
            client,
            authorization,
            poll_interval,
        })
    }

    /// Polls `/token` once for the supplied flow.
    pub fn poll_token_once(
        &self,
        flow: &KiroDeviceFlow,
        current_interval: Duration,
    ) -> KiroAuthSupportResult<KiroTokenPoll> {
        let body = TokenRequest {
            client_id: flow.client.client_id.clone(),
            client_secret: flow.client.client_secret.clone(),
            device_code: flow.authorization.device_code.clone(),
            grant_type: DEVICE_CODE_GRANT_TYPE.to_owned(),
        };
        let response = self.http.post("/token")?.json(&body).send()?;
        let response: KiroTokenResponse = HttpClient::read_json(response)?;
        Ok(map_token_response(response, current_interval))
    }

    /// Polls until the provider returns success, expiration, error, or local timeout.
    pub fn poll_until_terminal(
        &self,
        flow: &KiroDeviceFlow,
    ) -> KiroAuthSupportResult<KiroTokenPoll> {
        let started = Instant::now();
        let mut interval = flow.poll_interval;

        while started.elapsed() < self.config.poll_timeout {
            match self.poll_token_once(flow, interval)? {
                KiroTokenPoll::Pending => {}
                KiroTokenPoll::SlowDown { next_interval } => {
                    interval = next_interval;
                }
                terminal => return Ok(terminal),
            }
            thread::sleep(interval);
        }

        Ok(KiroTokenPoll::Expired {
            message: "poll timeout".to_owned(),
        })
    }
}

/// Non-blocking session status used by [`KiroDeviceFlowManager`].
#[apply(plain_partial_eq_display)]
pub enum KiroDeviceFlowSessionStatus {
    /// Polling is active.
    #[display("pending")]
    Pending,
    /// Token exchange completed.
    #[display("success")]
    Success(KiroTokenResponse),
    /// Device code expired or local timeout elapsed.
    #[display("expired")]
    Expired(String),
    /// Provider or transport error.
    #[display("error")]
    Error(String),
    /// Polling was canceled locally.
    #[display("canceled")]
    Canceled,
}

/// Snapshot returned by [`KiroDeviceFlowManager::get_status`].
#[apply(plain_partial_eq)]
pub struct KiroDeviceFlowSessionSnapshot {
    /// Local UUID for the flow.
    pub uuid: String,
    /// Current status.
    pub status: KiroDeviceFlowSessionStatus,
    /// URL the user should open while status is pending.
    pub verification_url: String,
    /// User code shown by the provider.
    pub user_code: String,
    /// Login type selected for the flow.
    pub login_type: KiroLoginType,
}

#[derive(Debug)]
pub struct KiroDeviceFlowSession {
    flow: KiroDeviceFlow,
    status: KiroDeviceFlowSessionStatus,
    cancel_requested: bool,
    handle: Option<JoinHandle<()>>,
}

impl KiroDeviceFlowSession {
    fn snapshot(&self) -> KiroDeviceFlowSessionSnapshot {
        KiroDeviceFlowSessionSnapshot {
            uuid: self.flow.uuid.clone(),
            status: self.status.clone(),
            verification_url: self.flow.verification_url().to_owned(),
            user_code: self.flow.user_code().to_owned(),
            login_type: self.flow.login_type,
        }
    }
}

/// Session manager that mirrors the Python module's `uuid -> status` workflow.
#[apply(plain_clone_debug)]
pub struct KiroDeviceFlowManager {
    client: KiroDeviceFlowClient,
    sessions: Arc<Mutex<HashMap<String, KiroDeviceFlowSession>>>,
}

impl KiroDeviceFlowManager {
    /// Creates a manager around a blocking device-flow client.
    #[must_use]
    pub fn new(client: KiroDeviceFlowClient) -> Self {
        Self {
            client,
            sessions: Arc::new(Mutex::new(HashMap::new())),
        }
    }

    /// Starts a device flow and returns its initial status snapshot.
    pub fn create_deviceflow_auth(
        &self,
        login_type: KiroLoginType,
        enterprise_start_url: Option<&str>,
    ) -> KiroAuthSupportResult<KiroDeviceFlowSessionSnapshot> {
        let flow = self
            .client
            .begin_device_flow(login_type, enterprise_start_url)?;
        let uuid = flow.uuid.clone();

        {
            let mut guard = self.sessions.lock().map_err(lock_error)?;
            guard.insert(
                uuid.clone(),
                KiroDeviceFlowSession {
                    flow: flow.clone(),
                    status: KiroDeviceFlowSessionStatus::Pending,
                    cancel_requested: false,
                    handle: None,
                },
            );
        }

        let client = self.client.clone();
        let sessions = Arc::clone(&self.sessions);
        let thread_uuid = uuid.clone();
        let handle = thread::spawn(move || {
            let terminal = match client.poll_until_terminal(&flow) {
                Ok(KiroTokenPoll::Success(response)) => {
                    KiroDeviceFlowSessionStatus::Success(response)
                }
                Ok(KiroTokenPoll::Expired { message }) => {
                    KiroDeviceFlowSessionStatus::Expired(message)
                }
                Ok(KiroTokenPoll::Error { message, .. }) => {
                    KiroDeviceFlowSessionStatus::Error(message)
                }
                Ok(KiroTokenPoll::Pending | KiroTokenPoll::SlowDown { .. }) => {
                    KiroDeviceFlowSessionStatus::Expired(
                        "poll finished without terminal status".to_owned(),
                    )
                }
                Err(error) => KiroDeviceFlowSessionStatus::Error(error.to_string()),
            };
            let Ok(mut guard) = sessions.lock() else {
                return;
            };
            let Some(session) = guard.get_mut(&thread_uuid) else {
                return;
            };
            if session.cancel_requested {
                return;
            }
            session.status = terminal;
        });

        let mut guard = self.sessions.lock().map_err(lock_error)?;
        let session = guard.get_mut(&uuid).ok_or_else(|| {
            KiroAuthSupportError::InvalidResponse("device flow session disappeared".to_owned())
        })?;
        session.handle = Some(handle);
        Ok(session.snapshot())
    }

    /// Gets the current status snapshot for a flow UUID.
    pub fn get_status(
        &self,
        uuid: impl AsRef<str>,
    ) -> KiroAuthSupportResult<Option<KiroDeviceFlowSessionSnapshot>> {
        let guard = self.sessions.lock().map_err(lock_error)?;
        Ok(guard
            .get(uuid.as_ref())
            .map(KiroDeviceFlowSession::snapshot))
    }

    /// Cancels a pending session locally.
    pub fn cancel(&self, uuid: impl AsRef<str>) -> KiroAuthSupportResult<bool> {
        let mut guard = self.sessions.lock().map_err(lock_error)?;
        let Some(session) = guard.get_mut(uuid.as_ref()) else {
            return Ok(false);
        };
        session.cancel_requested = true;
        if matches!(session.status, KiroDeviceFlowSessionStatus::Pending) {
            session.status = KiroDeviceFlowSessionStatus::Canceled;
        }
        Ok(true)
    }

    /// Removes a session from the manager.
    pub fn cleanup(&self, uuid: impl AsRef<str>) -> KiroAuthSupportResult<bool> {
        let mut guard = self.sessions.lock().map_err(lock_error)?;
        Ok(guard.remove(uuid.as_ref()).is_some())
    }
}

#[apply(serialize_eq)]
#[serde(rename_all = "camelCase")]
struct RegisterClientRequest {
    client_name: String,
    client_type: String,
    issuer_url: String,
    scopes: Vec<String>,
}

#[apply(serialize_eq)]
#[serde(rename_all = "camelCase")]
struct DeviceAuthorizationRequest {
    client_id: String,
    client_secret: String,
    start_url: String,
}

#[apply(serialize_eq)]
#[serde(rename_all = "camelCase")]
struct TokenRequest {
    client_id: String,
    client_secret: String,
    device_code: String,
    grant_type: String,
}

fn map_token_response(response: KiroTokenResponse, current_interval: Duration) -> KiroTokenPoll {
    if response.is_success() {
        return KiroTokenPoll::Success(response);
    }

    match response.error.as_deref().unwrap_or_default() {
        "authorization_pending" => KiroTokenPoll::Pending,
        "slow_down" => KiroTokenPoll::SlowDown {
            next_interval: (current_interval + Duration::from_secs(2)).min(Duration::from_secs(10)),
        },
        "expired_token" => KiroTokenPoll::Expired {
            message: response
                .error_description
                .clone()
                .unwrap_or_else(|| "device code expired".to_owned()),
        },
        "" => KiroTokenPoll::Error {
            message: "token response did not contain accessToken or OAuth error".to_owned(),
            response,
        },
        _ => KiroTokenPoll::Error {
            message: response
                .error_description
                .clone()
                .or_else(|| response.error.clone())
                .unwrap_or_else(|| "unknown token error".to_owned()),
            response,
        },
    }
}

fn lock_error<T>(_error: T) -> KiroAuthSupportError {
    KiroAuthSupportError::InvalidConfig("device flow session lock poisoned".to_owned())
}

#[cfg(test)]
mod tests {
    use super::{map_token_response, KiroDeviceFlowClient, KiroLoginType, KiroTokenPoll};
    use crate::KiroOidcConfig;
    use std::time::Duration;

    #[test]
    fn enterprise_start_url_requires_https() {
        assert_eq!(
            KiroLoginType::Enterprise.resolve_start_url(Some("http://bad")),
            "https://d-906600eb6f.awsapps.com/start"
        );
        assert_eq!(
            KiroLoginType::Enterprise.resolve_start_url(Some("https://example.awsapps.com/start/")),
            "https://example.awsapps.com/start"
        );
    }

    #[test]
    fn slow_down_increases_poll_interval() {
        let poll = map_token_response(
            super::KiroTokenResponse {
                error: Some("slow_down".to_owned()),
                ..super::KiroTokenResponse::default()
            },
            Duration::from_secs(2),
        );

        assert_eq!(
            poll,
            KiroTokenPoll::SlowDown {
                next_interval: Duration::from_secs(4)
            }
        );
    }

    #[test]
    fn client_builds_from_default_config() {
        let client = KiroDeviceFlowClient::new(KiroOidcConfig::default());

        assert!(client.is_ok());
    }
}
