[package]
name = "az-creates"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
automod.workspace = true
anyhow.workspace = true
az-derive-aliases.workspace = true
az-email.workspace = true
az-maven.workspace = true
az-music.workspace = true
az-str.workspace = true
az-sms.workspace = true
az-temp-mail.workspace = true
chrono.workspace = true
hmac.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[lints]
workspace = true
