[workspace]
resolver = "3"
members = [
    "crates/app",
    "crates/pay-api",
    "crates/inventory-plugin-alipay",
    "crates/inventory-plugin-wechat",
    "crates/inventory-plugin-other",
]

[workspace.dependencies]
automod = { package = "az-automod", version = "=2026.6.15", path = "../../crates/core/automod" }
