[package]
name = "az-derive-aliases"
description = "Reusable macro aliases for repetitive derive bundles and helper attributes"
version = "2026.6.13"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
automod.workspace = true
derive_more.workspace = true
clap.workspace = true
macro_rules_attribute.workspace = true
serde.workspace = true
strum.workspace = true

[dev-dependencies]
anyhow.workspace = true
serde_json.workspace = true

[lints]
workspace = true
