[package]
name = "az-derive-aliases"
description = "Reusable macro aliases for repetitive derive bundles and helper attributes"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
derive_more.workspace = true
clap.workspace = true
macro_rules_attribute.workspace = true
serde.workspace = true
strum.workspace = true
thiserror.workspace = true

[lints]
workspace = true
