[package]
name = "study-toasty"
version = "0.1.0"
edition = "2024"
rust-version = "1.95"
publish = false

[workspace]

[dependencies]
anyhow = "1.0.99"
toasty = { version = "0.6.1", features = ["postgresql"] }
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread"] }
uuid = { version = "1.23.0", features = ["v4"] }
