[package]
name = "az-face-detection"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Local SCRFD face detection inference"
homepage.workspace = true
repository.workspace = true

[dependencies]
automod.workspace = true
base64.workspace = true
image.workspace = true
imageproc.workspace = true
ndarray.workspace = true
ort.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
