use anyhow::Context;
use async_openai::types::responses::FunctionCallOutput;
use serde::Deserialize;
use serde_json::{Value, json};

pub mod current_time;
pub mod workspace;

/// A model-callable Responses API function tool.
pub trait AgentTool {
    /// Stable function name exposed to the model.
    fn name(&self) -> &'static str;

    /// Function description exposed to the model.
    fn description(&self) -> &'static str;

    /// JSON Schema for function arguments.
    fn parameters_schema(&self) -> Value;

    /// Executes a function call with raw JSON arguments from the model.
    fn execute(&self, arguments: &str) -> anyhow::Result<FunctionCallOutput>;

    /// Converts this tool to a Responses API `tools[]` item.
    fn definition(&self) -> Value {
        json!({
            "type": "function",
            "name": self.name(),
            "description": self.description(),
            "parameters": self.parameters_schema(),
            "strict": true,
        })
    }
}

/// Plugin-style registry for agent tools.
#[derive(Clone)]
pub struct ToolRegistry {
    tools: Vec<std::sync::Arc<dyn AgentTool + Send + Sync>>,
}

impl ToolRegistry {
    /// Creates a registry from explicit tool plugins.
    pub fn new(tools: Vec<std::sync::Arc<dyn AgentTool + Send + Sync>>) -> Self {
        Self { tools }
    }

    /// Returns Responses API function tool definitions.
    pub fn definitions(&self) -> Vec<Value> {
        self.tools.iter().map(|tool| tool.definition()).collect()
    }

    /// Executes a registered tool by name.
    pub fn execute(&self, call: &FunctionToolCall) -> anyhow::Result<FunctionCallOutput> {
        let tool = self
            .tools
            .iter()
            .find(|tool| tool.name() == call.name)
            .ok_or_else(|| anyhow::anyhow!("unsupported tool call `{}`", call.name))?;
        tool.execute(&call.arguments)
            .with_context(|| format!("execute tool `{}`", call.name))
    }

    /// Returns the preferred demo tool name.
    pub fn default_tool_choice(&self) -> &'static str {
        current_time::TOOL_NAME
    }

    /// Executes the local time fallback when a provider ignores tool calling.
    pub fn current_time_fallback(&self) -> anyhow::Result<FunctionCallOutput> {
        let call = FunctionToolCall {
            call_id: "local_fallback".to_string(),
            name: current_time::TOOL_NAME.to_string(),
            arguments: r#"{"timezone_hint":""}"#.to_string(),
        };
        self.execute(&call)
    }
}

/// Function call item returned by the Responses API.
#[derive(Debug, Clone, Deserialize)]
pub struct FunctionToolCall {
    /// Correlation ID required in `function_call_output`.
    pub call_id: String,
    /// Function name selected by the model.
    pub name: String,
    /// JSON string arguments generated by the model.
    pub arguments: String,
}

/// Formats function output for direct CLI fallback display.
pub fn format_function_output(output: FunctionCallOutput) -> anyhow::Result<String> {
    match output {
        FunctionCallOutput::Text(text) => {
            let value =
                serde_json::from_str::<Value>(&text).context("parse function output JSON")?;
            Ok(serde_json::to_string_pretty(&value)?)
        }
        FunctionCallOutput::Content(content) => Ok(serde_json::to_string_pretty(
            &serde_json::to_value(content)?,
        )?),
    }
}

pub(crate) fn parse_tool_arguments(arguments: &str, tool_name: &str) -> anyhow::Result<Value> {
    serde_json::from_str::<Value>(arguments)
        .with_context(|| format!("parse arguments for tool `{tool_name}`"))
}

pub(crate) fn argument_string(arguments: &Value, name: &str) -> String {
    arguments
        .get(name)
        .and_then(Value::as_str)
        .unwrap_or_default()
        .to_string()
}

pub(crate) fn argument_bool(arguments: &Value, name: &str) -> bool {
    arguments
        .get(name)
        .and_then(Value::as_bool)
        .unwrap_or(false)
}

pub(crate) fn json_output(value: Value) -> FunctionCallOutput {
    value.to_string().into()
}
