[package]
name = "az-ai-chat"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "AI/LLM 供应商统一聊天接口，覆盖 OpenAI 兼容接口、Claude 和 Gemini。"

[dependencies]
anyhow.workspace = true
automod.workspace = true
az-derive-aliases.workspace = true
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
tokio.workspace = true
strum.workspace = true

[lints]
workspace = true
