[package]
name = "az-software-catalog"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
automod.workspace = true
az-derive-aliases.workspace = true
derive_more.workspace = true
serde = { workspace = true, features = ["derive"] }
strum.workspace = true
thiserror.workspace = true
uuid.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
az-persistence.workspace = true
chrono = { workspace = true, features = ["serde"] }
regex.workspace = true
reqwest.workspace = true
sea-orm.workspace = true
serde_json.workspace = true

[lints]
workspace = true
