[package]
name = "az-aio-plugin-catalog"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "AZ AIO plugin catalog runtime plugin."

[lib]
crate-type = ["rlib"]

[dependencies]
automod.workspace = true
anyhow.workspace = true
az-aio-plugin-api = { path = "../../api" }

[lints.clippy]
dbg_macro = "deny"
todo = "deny"
