[package]
name = "az-sql"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "SQL query builder with type-safe SQL construction"

[dependencies]
anyhow.workspace = true
automod.workspace = true
derive_more.workspace = true
serde.workspace = true
strum.workspace = true

[lints]
workspace = true
