[package]
name = "az-aio-plugin-core-nav"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Built-in AZ AIO desktop navigation plugin."

[dependencies]
az-aio-plugin-api = { path = "../../api" }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
dbg_macro = "deny"
todo = "deny"
