[package]
name = "az-email"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
az-derive-aliases.workspace = true
derive_more.workspace = true
lettre.workspace = true
mime_guess.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
