[package]
name = "az-area"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
az-derive-aliases.workspace = true
automod.workspace = true

[dev-dependencies]
az-derive-aliases.workspace = true

[lints]
workspace = true
