// Generated from OpenAPI spec. Do not edit by hand.
//! `ApplyPatchToolCallOutput` DTO.

use serde::{Deserialize, Serialize};

use crate::models::{
    ApplyPatchCallOutputStatus,
};

/// The output emitted by an apply patch tool call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApplyPatchToolCallOutput {
    /// The type of the item. Always `apply_patch_call_output`.
    #[serde(rename = "type")]
    pub type_value: String,
    /// The unique ID of the apply patch tool call output. Populated when this item is returned via API.
    pub id: String,
    /// The unique ID of the apply patch tool call generated by the model.
    pub call_id: String,
    /// The status of the apply patch tool call output. One of `completed` or `failed`.
    pub status: ApplyPatchCallOutputStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output: Option<String>,
    /// The ID of the entity that created this tool call output.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
}
