// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
//! `ApplyPatchToolCallOutputItemParam` DTO.

use serde::{Deserialize, Serialize};

use crate::models::{
    ApplyPatchCallOutputStatusParam,
};

/// The streamed output emitted by an apply patch tool call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApplyPatchToolCallOutputItemParam {
    /// The type of the item. Always `apply_patch_call_output`.
    #[serde(rename = "type")]
    pub type_value: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The unique ID of the apply patch tool call generated by the model.
    pub call_id: String,
    /// The status of the apply patch tool call output. One of `completed` or `failed`.
    pub status: ApplyPatchCallOutputStatusParam,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output: Option<String>,
}
