// Generated from OpenAPI spec. Do not edit by hand.
//! `ApplyPatchToolCall` DTO.

use serde::{Deserialize, Serialize};

use crate::models::{
    ApplyPatchCallStatus,
    ApplyPatchToolCallOperation,
};

/// A tool call that applies file diffs by creating, deleting, or updating files.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApplyPatchToolCall {
    /// The type of the item. Always `apply_patch_call`.
    #[serde(rename = "type")]
    pub type_value: String,
    /// The unique ID of the apply patch tool call. Populated when this item is returned via API.
    pub id: String,
    /// The unique ID of the apply patch tool call generated by the model.
    pub call_id: String,
    /// The status of the apply patch tool call. One of `in_progress` or `completed`.
    pub status: ApplyPatchCallStatus,
    /// One of the create_file, delete_file, or update_file operations applied via apply_patch.
    pub operation: ApplyPatchToolCallOperation,
    /// The ID of the entity that created this tool call.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
}
