// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
//! `ApplyPatchToolCallItemParam` DTO.

use serde::{Deserialize, Serialize};

use crate::models::{
    ApplyPatchCallStatusParam,
    ApplyPatchOperationParam,
};

/// A tool call representing a request to create, delete, or update files using diff patches.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ApplyPatchToolCallItemParam {
    /// The type of the item. Always `apply_patch_call`.
    #[serde(rename = "type")]
    pub type_value: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The unique ID of the apply patch tool call generated by the model.
    pub call_id: String,
    /// The status of the apply patch tool call. One of `in_progress` or `completed`.
    pub status: ApplyPatchCallStatusParam,
    /// The specific create, delete, or update instruction for the apply_patch tool call.
    pub operation: ApplyPatchOperationParam,
}
