// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
//! `ChatCompletionMessageListDataItemAudio` DTO.

use serde::{Deserialize, Serialize};

/// If the audio output modality is requested, this object contains data about the audio response from
/// the model. [Learn more](/docs/guides/audio).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatCompletionMessageListDataItemAudio {
    /// Unique identifier for this audio response.
    pub id: String,
    /// The Unix timestamp (in seconds) for when this audio response will no longer be accessible on the
    /// server for use in multi-turn conversations.
    pub expires_at: i64,
    /// Base64 encoded audio bytes generated by the model, in the format specified in the request.
    pub data: String,
    /// Transcript of the audio generated by the model.
    pub transcript: String,
}
