// Generated from OpenAPI spec. Do not edit by hand.
//! `ChatCompletionMessageToolCalls` DTO.

use crate::models::{
    ChatCompletionMessageToolCall2,
};

/// The tool calls generated by the model, such as function calls.
pub type ChatCompletionMessageToolCalls = Vec<ChatCompletionMessageToolCall2>;
