// Generated from OpenAPI spec. Do not edit by hand.
//! `ChatCompletionResponseMessageFunctionCall` DTO.

use serde::{Deserialize, Serialize};

/// Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called,
/// as generated by the model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatCompletionResponseMessageFunctionCall {
    /// The arguments to call the function with, as generated by the model in JSON format. Note that the
    /// model does not always generate valid JSON, and may hallucinate parameters not defined by your
    /// function schema. Validate the arguments in your code before calling your function.
    pub arguments: String,
    /// The name of the function to call.
    pub name: String,
}
