// Generated from OpenAPI spec. Do not edit by hand.
//! `ChatCompletionMessageCustomToolCallCustom` DTO.

use serde::{Deserialize, Serialize};

/// The custom tool that the model called.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatCompletionMessageCustomToolCallCustom {
    /// The name of the custom tool to call.
    pub name: String,
    /// The input for the custom tool call generated by the model.
    pub input: String,
}
