// Generated from OpenAPI spec. Do not edit by hand.
//! `ChatCompletionResponseMessage` DTO.

use serde::{Deserialize, Serialize};

use crate::models::{
    ChatCompletionMessageToolCalls,
    ChatCompletionResponseMessageAnnotation,
    ChatCompletionResponseMessageAudio,
    ChatCompletionResponseMessageFunctionCall,
};

/// A chat completion message generated by the model.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatCompletionResponseMessage {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub refusal: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<ChatCompletionMessageToolCalls>,
    /// Annotations for the message, when applicable, as when using the [web search
    /// tool](/docs/guides/tools-web-search?api-mode=chat).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub annotations: Option<Vec<ChatCompletionResponseMessageAnnotation>>,
    /// The role of the author of this message.
    pub role: String,
    /// Deprecated and replaced by `tool_calls`. The name and arguments of a function that should be called,
    /// as generated by the model.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub function_call: Option<ChatCompletionResponseMessageFunctionCall>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub audio: Option<ChatCompletionResponseMessageAudio>,
}
