// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
//! `ChatCompletionRequestMessageContentPartRefusal` DTO.

use serde::{Deserialize, Serialize};

/// Refusal content part
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatCompletionRequestMessageContentPartRefusal {
    /// The type of the content part.
    #[serde(rename = "type")]
    pub type_value: String,
    /// The refusal message generated by the model.
    pub refusal: String,
}
