// Generated from OpenAPI spec. Do not edit by hand.
//! `ChatCompletionMessageToolCallChunkFunction` DTO.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChatCompletionMessageToolCallChunkFunction {
    /// The name of the function to call.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The arguments to call the function with, as generated by the model in JSON format. Note that the
    /// model does not always generate valid JSON, and may hallucinate parameters not defined by your
    /// function schema. Validate the arguments in your code before calling your function.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub arguments: Option<String>,
}
