// Generated from OpenAPI spec. Do not edit by hand.
//! `CompactionSummaryItemParam` DTO.

use serde::{Deserialize, Serialize};

/// A compaction item generated by the [`v1/responses/compact` API](/docs/api-
/// reference/responses/compact).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompactionSummaryItemParam {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The type of the item. Always `compaction`.
    #[serde(rename = "type")]
    pub type_value: String,
    /// The encrypted content of the compaction summary.
    pub encrypted_content: String,
}
