// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
//! `CompletionUsageCompletionTokensDetails` DTO.

use serde::{Deserialize, Serialize};

/// Breakdown of tokens used in a completion.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompletionUsageCompletionTokensDetails {
    /// When using Predicted Outputs, the number of tokens in the prediction that appeared in the
    /// completion.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub accepted_prediction_tokens: Option<i32>,
    /// Audio input tokens generated by the model.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub audio_tokens: Option<i32>,
    /// Tokens generated by the model for reasoning.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reasoning_tokens: Option<i32>,
    /// When using Predicted Outputs, the number of tokens in the prediction that did not appear in the
    /// completion. However, like reasoning tokens, these tokens are still counted in the total completion
    /// tokens for purposes of billing, output, and context window limits.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rejected_prediction_tokens: Option<i32>,
}
