// Generated from OpenAPI spec. Do not edit by hand.
//! `CompactionBody` DTO.

use serde::{Deserialize, Serialize};

/// A compaction item generated by the [`v1/responses/compact` API](/docs/api-
/// reference/responses/compact).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CompactionBody {
    /// The type of the item. Always `compaction`.
    #[serde(rename = "type")]
    pub type_value: String,
    /// The unique ID of the compaction item.
    pub id: String,
    /// The encrypted content that was produced by compaction.
    pub encrypted_content: String,
    /// The identifier of the actor that created the item.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
}
