// Generated from OpenAPI spec. Do not edit by hand.
//! `CreateMessageRequest` DTO.

use serde::{Deserialize, Serialize};

use crate::models::{
    CreateMessageRequestAttachment,
    CreateMessageRequestContent,
    Metadata,
};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateMessageRequest {
    /// The role of the entity that is creating the message. Allowed values include: - `user`: Indicates the
    /// message is sent by an actual user and should be used in most cases to represent user-generated
    /// messages. - `assistant`: Indicates the message is generated by the assistant. Use this value to
    /// insert messages from the assistant into the conversation.
    pub role: String,
    pub content: CreateMessageRequestContent,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub attachments: Option<Vec<CreateMessageRequestAttachment>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Metadata>,
}
