// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
//! `CreateEmbeddingResponse` DTO.

use serde::{Deserialize, Serialize};

use crate::models::{
    CreateEmbeddingResponseUsage,
    Embedding,
};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateEmbeddingResponse {
    /// The list of embeddings generated by the model.
    pub data: Vec<Embedding>,
    /// The name of the model used to generate the embedding.
    pub model: String,
    /// The object type, which is always "list".
    pub object: String,
    /// The usage information for the request.
    pub usage: CreateEmbeddingResponseUsage,
}
