// Generated from OpenAPI spec. Do not edit by hand.
//! `CreateImageRequest` DTO.

use serde::{Deserialize, Serialize};

use crate::models::{
    PartialImages,
};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateImageRequest {
    /// A text description of the desired image(s). The maximum length is 32000 characters for the GPT image
    /// models, 1000 characters for `dall-e-2` and 4000 characters for `dall-e-3`.
    pub prompt: String,
    /// The model to use for image generation. One of `dall-e-2`, `dall-e-3`, or a GPT image model (`gpt-
    /// image-1`, `gpt-image-1-mini`, `gpt-image-1.5`). Defaults to `dall-e-2` unless a parameter specific
    /// to the GPT image models is used.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<String>,
    /// The number of images to generate. Must be between 1 and 10. For `dall-e-3`, only `n=1` is supported.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub n: Option<i32>,
    /// The quality of the image that will be generated. - `auto` (default value) will automatically select
    /// the best quality for the given model. - `high`, `medium` and `low` are supported for the GPT image
    /// models. - `hd` and `standard` are supported for `dall-e-3`. - `standard` is the only option for
    /// `dall-e-2`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub quality: Option<String>,
    /// The format in which generated images with `dall-e-2` and `dall-e-3` are returned. Must be one of
    /// `url` or `b64_json`. URLs are only valid for 60 minutes after the image has been generated. This
    /// parameter isn't supported for the GPT image models, which always return base64-encoded images.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub response_format: Option<String>,
    /// The format in which the generated images are returned. This parameter is only supported for the GPT
    /// image models. Must be one of `png`, `jpeg`, or `webp`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output_format: Option<String>,
    /// The compression level (0-100%) for the generated images. This parameter is only supported for the
    /// GPT image models with the `webp` or `jpeg` output formats, and defaults to 100.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output_compression: Option<i32>,
    /// Generate the image in streaming mode. Defaults to `false`. See the [Image generation
    /// guide](/docs/guides/image-generation) for more information. This parameter is only supported for the
    /// GPT image models.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stream: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub partial_images: Option<PartialImages>,
    /// The size of the generated images. For `gpt-image-2` and `gpt-image-2-2026-04-21`, arbitrary
    /// resolutions are supported as `WIDTHxHEIGHT` strings, for example `1536x864`. Width and height must
    /// both be divisible by 16 and the requested aspect ratio must be between 1:3 and 3:1. Resolutions
    /// above `2560x1440` are experimental, and the maximum supported resolution is `3840x2160`. The
    /// requested size must also satisfy the model's current pixel and edge limits. The standard sizes
    /// `1024x1024`, `1536x1024`, and `1024x1536` are supported by the GPT image models; `auto` is supported
    /// for models that allow automatic sizing. For `dall-e-2`, use one of `256x256`, `512x512`, or
    /// `1024x1024`. For `dall-e-3`, use one of `1024x1024`, `1792x1024`, or `1024x1792`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub size: Option<String>,
    /// Control the content-moderation level for images generated by the GPT image models. Must be either
    /// `low` for less restrictive filtering or `auto` (default value).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub moderation: Option<String>,
    /// Allows to set transparency for the background of the generated image(s). This parameter is only
    /// supported for the GPT image models. Must be one of `transparent`, `opaque` or `auto` (default
    /// value). When `auto` is used, the model will automatically determine the best background for the
    /// image. If `transparent`, the output format needs to support transparency, so it should be set to
    /// either `png` (default value) or `webp`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub background: Option<String>,
    /// The style of the generated images. This parameter is only supported for `dall-e-3`. Must be one of
    /// `vivid` or `natural`. Vivid causes the model to lean towards generating hyper-real and dramatic
    /// images. Natural causes the model to produce more natural, less hyper-real looking images.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub style: Option<String>,
    /// A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse.
    /// [Learn more](/docs/guides/safety-best-practices#end-user-ids).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,
}
