// Generated from OpenAPI spec. Do not edit by hand.
//! `CreateFineTuningJobRequestIntegrationWandb` DTO.

use serde::{Deserialize, Serialize};

/// The settings for your integration with Weights and Biases. This payload specifies the project that
/// metrics will be sent to. Optionally, you can set an explicit display name for your run, add tags to
/// your run, and set a default entity (team, username, etc) to be associated with your run.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CreateFineTuningJobRequestIntegrationWandb {
    /// The name of the project that the new run will be created under.
    pub project: String,
    /// A display name to set for the run. If not set, we will use the Job ID as the name.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// The entity to use for the run. This allows you to set the team or username of the WandB user that
    /// you would like associated with the run. If not set, the default entity for the registered WandB API
    /// key is used.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub entity: Option<String>,
    /// A list of tags to be attached to the newly created run. These tags are passed through directly to
    /// WandB. Some default tags are generated by OpenAI: "openai/finetune", "openai/{base-model}",
    /// "openai/{ftjob-abcdef}".
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}
