// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
//! `CustomToolCallOutputOutput` DTO.

use serde::{Deserialize, Serialize};

use crate::models::{
    FunctionAndCustomToolCallOutput,
};

/// The output from the custom tool call generated by your code. Can be a string or an list of output
/// content.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum CustomToolCallOutputOutput {
    StringOutput(String),
    OutputContentList(Vec<FunctionAndCustomToolCallOutput>),
}
