// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
//! `CustomToolCallResource` DTO.

use serde::{Deserialize, Serialize};

use crate::models::{
    FunctionCallStatus,
};

/// ResponseCustomToolCallItem
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CustomToolCallResource {
    /// The type of the custom tool call. Always `custom_tool_call`.
    #[serde(rename = "type")]
    pub type_value: String,
    /// The unique ID of the custom tool call in the OpenAI platform.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// An identifier used to map this custom tool call to a tool call output.
    pub call_id: String,
    /// The namespace of the custom tool being called.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    /// The name of the custom tool being called.
    pub name: String,
    /// The input for the custom tool call generated by the model.
    pub input: String,
    /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are
    /// returned via API.
    pub status: FunctionCallStatus,
    /// The identifier of the actor that created the item.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
}
