// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
//! `CustomToolCallOutputResource` DTO.

use serde::{Deserialize, Serialize};

use crate::models::{
    CustomToolCallOutputResourceOutput,
    FunctionCallOutputStatusEnum,
};

/// ResponseCustomToolCallOutputItem
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CustomToolCallOutputResource {
    /// The type of the custom tool call output. Always `custom_tool_call_output`.
    #[serde(rename = "type")]
    pub type_value: String,
    /// The unique ID of the custom tool call output in the OpenAI platform.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The call ID, used to map this custom tool call output to a custom tool call.
    pub call_id: String,
    /// The output from the custom tool call generated by your code. Can be a string or an list of output
    /// content.
    pub output: CustomToolCallOutputResourceOutput,
    /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are
    /// returned via API.
    pub status: FunctionCallOutputStatusEnum,
    /// The identifier of the actor that created the item.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
}
