// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
//! `EasyInputMessage` DTO.

use serde::{Deserialize, Serialize};

use crate::models::{
    EasyInputMessageContent,
    MessagePhase,
};

/// A message input to the model with a role indicating instruction following hierarchy. Instructions
/// given with the `developer` or `system` role take precedence over instructions given with the `user`
/// role. Messages with the `assistant` role are presumed to have been generated by the model in
/// previous interactions.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EasyInputMessage {
    /// The role of the message input. One of `user`, `assistant`, `system`, or `developer`.
    pub role: String,
    /// Text, image, or audio input to the model, used to generate a response. Can also contain previous
    /// assistant responses.
    pub content: EasyInputMessageContent,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub phase: Option<MessagePhase>,
    /// The type of the message input. Always `message`.
    #[serde(rename = "type", default, skip_serializing_if = "Option::is_none")]
    pub type_value: Option<String>,
}
