// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
//! `FineTuningIntegrationWandb` DTO.

use serde::{Deserialize, Serialize};

/// The settings for your integration with Weights and Biases. This payload specifies the project that
/// metrics will be sent to. Optionally, you can set an explicit display name for your run, add tags to
/// your run, and set a default entity (team, username, etc) to be associated with your run.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FineTuningIntegrationWandb {
    /// The name of the project that the new run will be created under.
    pub project: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub entity: Option<String>,
    /// A list of tags to be attached to the newly created run. These tags are passed through directly to
    /// WandB. Some default tags are generated by OpenAI: "openai/finetune", "openai/{base-model}",
    /// "openai/{ftjob-abcdef}".
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}
