// Generated from OpenAPI spec. Do not edit by hand.
//! `FunctionCallOutputItemParam` DTO.

use serde::{Deserialize, Serialize};

use crate::models::{
    FunctionCallItemStatus,
    FunctionCallOutputItemParamOutput,
};

/// The output of a function tool call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionCallOutputItemParam {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The unique ID of the function tool call generated by the model.
    pub call_id: String,
    /// The type of the function tool call output. Always `function_call_output`.
    #[serde(rename = "type")]
    pub type_value: String,
    /// Text, image, or file output of the function tool call.
    pub output: FunctionCallOutputItemParamOutput,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<FunctionCallItemStatus>,
}
