// Generated from OpenAPI spec. Do not edit by hand.
//! `FunctionShellCallOutputItemParam` DTO.

use serde::{Deserialize, Serialize};

use crate::models::{
    FunctionShellCallItemStatus,
    FunctionShellCallOutputContentParam,
};

/// The streamed output items emitted by a shell tool call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionShellCallOutputItemParam {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The unique ID of the shell tool call generated by the model.
    pub call_id: String,
    /// The type of the item. Always `shell_call_output`.
    #[serde(rename = "type")]
    pub type_value: String,
    /// Captured chunks of stdout and stderr output, along with their associated outcomes.
    pub output: Vec<FunctionShellCallOutputContentParam>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<FunctionShellCallItemStatus>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_output_length: Option<i32>,
}
