// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
//! `FunctionShellCallOutput` DTO.

use serde::{Deserialize, Serialize};

use crate::models::{
    FunctionShellCallOutputContent,
    FunctionShellCallOutputStatusEnum,
};

/// The output of a shell tool call that was emitted.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionShellCallOutput {
    /// The type of the shell call output. Always `shell_call_output`.
    #[serde(rename = "type")]
    pub type_value: String,
    /// The unique ID of the shell call output. Populated when this item is returned via API.
    pub id: String,
    /// The unique ID of the shell tool call generated by the model.
    pub call_id: String,
    /// The status of the shell call output. One of `in_progress`, `completed`, or `incomplete`.
    pub status: FunctionShellCallOutputStatusEnum,
    /// An array of shell call output contents
    pub output: Vec<FunctionShellCallOutputContent>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_output_length: Option<i32>,
    /// The identifier of the actor that created the item.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
}
