// Generated from OpenAPI spec. Do not edit by hand.
//! `FunctionShellCall` DTO.

use serde::{Deserialize, Serialize};

use crate::models::{
    FunctionShellAction,
    FunctionShellCallEnvironment,
    FunctionShellCallStatus,
};

/// A tool call that executes one or more shell commands in a managed environment.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionShellCall {
    /// The type of the item. Always `shell_call`.
    #[serde(rename = "type")]
    pub type_value: String,
    /// The unique ID of the shell tool call. Populated when this item is returned via API.
    pub id: String,
    /// The unique ID of the shell tool call generated by the model.
    pub call_id: String,
    /// The shell commands and limits that describe how to run the tool call.
    pub action: FunctionShellAction,
    /// The status of the shell call. One of `in_progress`, `completed`, or `incomplete`.
    pub status: FunctionShellCallStatus,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub environment: Option<FunctionShellCallEnvironment>,
    /// The ID of the entity that created this tool call.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
}
