// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
//! `FunctionToolCallOutputResource` DTO.

use serde::{Deserialize, Serialize};

use crate::models::{
    FunctionToolCallOutputResourceOutput,
};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionToolCallOutputResource {
    /// The unique ID of the function tool call output. Populated when this item is returned via API.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The type of the function tool call output. Always `function_call_output`.
    #[serde(rename = "type")]
    pub type_value: String,
    /// The unique ID of the function tool call generated by the model.
    pub call_id: String,
    /// The output from the function call generated by your code. Can be a string or an list of output
    /// content.
    pub output: FunctionToolCallOutputResourceOutput,
    /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are
    /// returned via API.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// The identifier of the actor that created the item.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
}
