// Generated from OpenAPI spec. Do not edit by hand.
//! `FunctionShellCallItemParam` DTO.

use serde::{Deserialize, Serialize};

use crate::models::{
    FunctionShellActionParam,
    FunctionShellCallItemParamEnvironment,
    FunctionShellCallItemStatus,
};

/// A tool representing a request to execute one or more shell commands.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionShellCallItemParam {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The unique ID of the shell tool call generated by the model.
    pub call_id: String,
    /// The type of the item. Always `shell_call`.
    #[serde(rename = "type")]
    pub type_value: String,
    /// The shell commands and limits that describe how to run the tool call.
    pub action: FunctionShellActionParam,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<FunctionShellCallItemStatus>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub environment: Option<FunctionShellCallItemParamEnvironment>,
}
