// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
//! `FunctionToolCall` DTO.

use serde::{Deserialize, Serialize};

/// A tool call to run a function. See the [function calling guide](/docs/guides/function-calling) for
/// more information.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionToolCall {
    /// The unique ID of the function tool call.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The type of the function tool call. Always `function_call`.
    #[serde(rename = "type")]
    pub type_value: String,
    /// The unique ID of the function tool call generated by the model.
    pub call_id: String,
    /// The namespace of the function to run.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    /// The name of the function to run.
    pub name: String,
    /// A JSON string of the arguments to pass to the function.
    pub arguments: String,
    /// The status of the item. One of `in_progress`, `completed`, or `incomplete`. Populated when items are
    /// returned via API.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}
