// Generated from OpenAPI spec. Do not edit by hand.
//! `FunctionToolCallOutputResourceOutput` DTO.

use serde::{Deserialize, Serialize};

use crate::models::{
    FunctionAndCustomToolCallOutput,
};

/// The output from the function call generated by your code. Can be a string or an list of output
/// content.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum FunctionToolCallOutputResourceOutput {
    StringOutput(String),
    OutputContentList(Vec<FunctionAndCustomToolCallOutput>),
}
