// Generated from OpenAPI spec. Do not edit by hand.
//! `ImageGenOutputTokensDetails` DTO.

use serde::{Deserialize, Serialize};

/// The output token details for the image generation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ImageGenOutputTokensDetails {
    /// The number of image output tokens generated by the model.
    pub image_tokens: i32,
    /// The number of text output tokens generated by the model.
    pub text_tokens: i32,
}
