// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
//! `Image` DTO.

use serde::{Deserialize, Serialize};

/// Represents the content or the URL of an image generated by the OpenAI API.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Image {
    /// The base64-encoded JSON of the generated image. Returned by default for the GPT image models, and
    /// only present if `response_format` is set to `b64_json` for `dall-e-2` and `dall-e-3`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub b64_json: Option<String>,
    /// When using `dall-e-2` or `dall-e-3`, the URL of the generated image if `response_format` is set to
    /// `url` (default value). Unsupported for the GPT image models.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// For `dall-e-3` only, the revised prompt that was used to generate the image.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revised_prompt: Option<String>,
}
