// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
//! `ImageGenUsage` DTO.

use serde::{Deserialize, Serialize};

use crate::models::{
    ImageGenInputUsageDetails,
    ImageGenOutputTokensDetails,
};

/// For `gpt-image-1` only, the token usage information for the image generation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ImageGenUsage {
    /// The number of tokens (images and text) in the input prompt.
    pub input_tokens: i32,
    /// The total number of tokens (images and text) used for the image generation.
    pub total_tokens: i32,
    /// The number of output tokens generated by the model.
    pub output_tokens: i32,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output_tokens_details: Option<ImageGenOutputTokensDetails>,
    pub input_tokens_details: ImageGenInputUsageDetails,
}
