// Generated from OpenAPI spec. Do not edit by hand.
//! `LocalShellToolCallOutput` DTO.

use serde::{Deserialize, Serialize};

/// The output of a local shell tool call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocalShellToolCallOutput {
    /// The type of the local shell tool call output. Always `local_shell_call_output`.
    #[serde(rename = "type")]
    pub type_value: String,
    /// The unique ID of the local shell tool call generated by the model.
    pub id: String,
    /// A JSON string of the output of the local shell tool call.
    pub output: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}
