// Generated from OpenAPI spec. Do not edit by hand.
//! `LocalShellToolCall` DTO.

use serde::{Deserialize, Serialize};

use crate::models::{
    LocalShellExecAction,
};

/// A tool call to run a command on the local shell.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LocalShellToolCall {
    /// The type of the local shell call. Always `local_shell_call`.
    #[serde(rename = "type")]
    pub type_value: String,
    /// The unique ID of the local shell call.
    pub id: String,
    /// The unique ID of the local shell tool call generated by the model.
    pub call_id: String,
    pub action: LocalShellExecAction,
    /// The status of the local shell call.
    pub status: String,
}
