// Generated from OpenAPI spec. Do not edit by hand.
//! `MessageContentRefusalObject` DTO.

use serde::{Deserialize, Serialize};

/// The refusal content generated by the assistant.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MessageContentRefusalObject {
    /// Always `refusal`.
    #[serde(rename = "type")]
    pub type_value: String,
    pub refusal: String,
}
