// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
//! `RealtimeResponse` DTO.

use serde::{Deserialize, Serialize};

use crate::models::{
    Metadata,
    RealtimeConversationItem,
    RealtimeResponseAudio,
    RealtimeResponseMaxOutputTokens,
    RealtimeResponseStatusDetails,
    RealtimeResponseUsage,
};

/// The response resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RealtimeResponse {
    /// The unique ID of the response, will look like `resp_1234`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The object type, must be `realtime.response`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    /// The final status of the response (`completed`, `cancelled`, `failed`, or `incomplete`,
    /// `in_progress`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Additional details about the status.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status_details: Option<RealtimeResponseStatusDetails>,
    /// The list of output items generated by the response.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output: Option<Vec<RealtimeConversationItem>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Metadata>,
    /// Configuration for audio output.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub audio: Option<RealtimeResponseAudio>,
    /// Usage statistics for the Response, this will correspond to billing. A Realtime API session will
    /// maintain a conversation context and append new Items to the Conversation, thus output from previous
    /// turns (text and audio tokens) will become the input for later turns.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub usage: Option<RealtimeResponseUsage>,
    /// Which conversation the response is added to, determined by the `conversation` field in the
    /// `response.create` event. If `auto`, the response will be added to the default conversation and the
    /// value of `conversation_id` will be an id like `conv_1234`. If `none`, the response will not be added
    /// to any conversation and the value of `conversation_id` will be `null`. If responses are being
    /// triggered automatically by VAD the response will be added to the default conversation
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conversation_id: Option<String>,
    /// The set of modalities the model used to respond, currently the only possible values are
    /// `[\"audio\"]`, `[\"text\"]`. Audio output always include a text transcript. Setting the output to
    /// mode `text` will disable audio output from the model.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output_modalities: Option<Vec<String>>,
    /// Maximum number of output tokens for a single assistant response, inclusive of tool calls, that was
    /// used in this response.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_output_tokens: Option<RealtimeResponseMaxOutputTokens>,
}
