// Generated from OpenAPI spec. Do not edit by hand.
//! `RealtimeCallCreateRequest` DTO.

use serde::{Deserialize, Serialize};

use crate::models::{
    RealtimeCallCreateRequestSession,
};

/// Parameters required to initiate a realtime call and receive the SDP answer needed to complete a
/// WebRTC peer connection. Provide an SDP offer generated by your client and optionally configure the
/// session that will answer the call.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RealtimeCallCreateRequest {
    /// WebRTC Session Description Protocol (SDP) offer generated by the caller.
    pub sdp: String,
    /// Optional session configuration to apply before the realtime session is created. Use the same
    /// parameters you would send in a [`create client secret`](/docs/api-reference/realtime-
    /// sessions/create-realtime-client-secret) request.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session: Option<RealtimeCallCreateRequestSession>,
}
