// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
//! `RealtimeConversationItemFunctionCallOutput` DTO.

use serde::{Deserialize, Serialize};

/// A function call output item in a Realtime conversation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RealtimeConversationItemFunctionCallOutput {
    /// The unique ID of the item. This may be provided by the client or generated by the server.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Identifier for the API object being returned - always `realtime.item`. Optional when creating a new
    /// item.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    /// The type of the item. Always `function_call_output`.
    #[serde(rename = "type")]
    pub type_value: String,
    /// The status of the item. Has no effect on the conversation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// The ID of the function call this output is for.
    pub call_id: String,
    /// The output of the function call, this is free text and can contain any information or simply be
    /// empty.
    pub output: String,
}
