// Generated from OpenAPI spec. Do not edit by hand.
//! `RealtimeConversationItemMessageAssistant` DTO.

use serde::{Deserialize, Serialize};

use crate::models::{
    RealtimeConversationItemMessageAssistantContentItem,
};

/// An assistant message item in a Realtime conversation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RealtimeConversationItemMessageAssistant {
    /// The unique ID of the item. This may be provided by the client or generated by the server.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Identifier for the API object being returned - always `realtime.item`. Optional when creating a new
    /// item.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    /// The type of the item. Always `message`.
    #[serde(rename = "type")]
    pub type_value: String,
    /// The status of the item. Has no effect on the conversation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// The role of the message sender. Always `assistant`.
    pub role: String,
    /// The content of the message.
    pub content: Vec<RealtimeConversationItemMessageAssistantContentItem>,
}
