// Generated from OpenAPI spec. Do not edit by hand.
//! `RealtimeConversationItemMessageSystem` DTO.

use serde::{Deserialize, Serialize};

use crate::models::{
    RealtimeConversationItemMessageSystemContentItem,
};

/// A system message in a Realtime conversation can be used to provide additional context or
/// instructions to the model. This is similar but distinct from the instruction prompt provided at the
/// start of a conversation, as system messages can be added at any point in the conversation. For major
/// changes to the conversation's behavior, use instructions, but for smaller updates (e.g. "the user is
/// now asking about a different topic"), use system messages.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RealtimeConversationItemMessageSystem {
    /// The unique ID of the item. This may be provided by the client or generated by the server.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Identifier for the API object being returned - always `realtime.item`. Optional when creating a new
    /// item.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    /// The type of the item. Always `message`.
    #[serde(rename = "type")]
    pub type_value: String,
    /// The status of the item. Has no effect on the conversation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// The role of the message sender. Always `system`.
    pub role: String,
    /// The content of the message.
    pub content: Vec<RealtimeConversationItemMessageSystemContentItem>,
}
