// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
//! `RealtimeConversationItemFunctionCall` DTO.

use serde::{Deserialize, Serialize};

/// A function call item in a Realtime conversation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RealtimeConversationItemFunctionCall {
    /// The unique ID of the item. This may be provided by the client or generated by the server.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Identifier for the API object being returned - always `realtime.item`. Optional when creating a new
    /// item.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    /// The type of the item. Always `function_call`.
    #[serde(rename = "type")]
    pub type_value: String,
    /// The status of the item. Has no effect on the conversation.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// The ID of the function call.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub call_id: Option<String>,
    /// The name of the function being called.
    pub name: String,
    /// The arguments of the function call. This is a JSON-encoded string representing the arguments passed
    /// to the function, for example `{"arg1": "value1", "arg2": 42}`.
    pub arguments: String,
}
