// Generated from openai/openai-openapi openapi.yaml. Do not edit by hand.
//! `RealtimeServerEvent` DTO.

use serde::{Deserialize, Serialize};

use crate::models::{
    RealtimeServerEventConversationCreated,
    RealtimeServerEventConversationItemAdded,
    RealtimeServerEventConversationItemCreated,
    RealtimeServerEventConversationItemDeleted,
    RealtimeServerEventConversationItemDone,
    RealtimeServerEventConversationItemInputAudioTranscriptionCompleted,
    RealtimeServerEventConversationItemInputAudioTranscriptionDelta,
    RealtimeServerEventConversationItemInputAudioTranscriptionFailed,
    RealtimeServerEventConversationItemInputAudioTranscriptionSegment,
    RealtimeServerEventConversationItemRetrieved,
    RealtimeServerEventConversationItemTruncated,
    RealtimeServerEventError,
    RealtimeServerEventInputAudioBufferCleared,
    RealtimeServerEventInputAudioBufferCommitted,
    RealtimeServerEventInputAudioBufferDtmfEventReceived,
    RealtimeServerEventInputAudioBufferSpeechStarted,
    RealtimeServerEventInputAudioBufferSpeechStopped,
    RealtimeServerEventInputAudioBufferTimeoutTriggered,
    RealtimeServerEventMCPListToolsCompleted,
    RealtimeServerEventMCPListToolsFailed,
    RealtimeServerEventMCPListToolsInProgress,
    RealtimeServerEventOutputAudioBufferCleared,
    RealtimeServerEventOutputAudioBufferStarted,
    RealtimeServerEventOutputAudioBufferStopped,
    RealtimeServerEventRateLimitsUpdated,
    RealtimeServerEventResponseAudioDelta,
    RealtimeServerEventResponseAudioDone,
    RealtimeServerEventResponseAudioTranscriptDelta,
    RealtimeServerEventResponseAudioTranscriptDone,
    RealtimeServerEventResponseContentPartAdded,
    RealtimeServerEventResponseContentPartDone,
    RealtimeServerEventResponseCreated,
    RealtimeServerEventResponseDone,
    RealtimeServerEventResponseFunctionCallArgumentsDelta,
    RealtimeServerEventResponseFunctionCallArgumentsDone,
    RealtimeServerEventResponseMCPCallArgumentsDelta,
    RealtimeServerEventResponseMCPCallArgumentsDone,
    RealtimeServerEventResponseMCPCallCompleted,
    RealtimeServerEventResponseMCPCallFailed,
    RealtimeServerEventResponseMCPCallInProgress,
    RealtimeServerEventResponseOutputItemAdded,
    RealtimeServerEventResponseOutputItemDone,
    RealtimeServerEventResponseTextDelta,
    RealtimeServerEventResponseTextDone,
    RealtimeServerEventSessionCreated,
    RealtimeServerEventSessionUpdated,
};

/// A realtime server event.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum RealtimeServerEvent {
    RealtimeServerEventConversationCreated(RealtimeServerEventConversationCreated),
    RealtimeServerEventConversationItemCreated(RealtimeServerEventConversationItemCreated),
    RealtimeServerEventConversationItemDeleted(RealtimeServerEventConversationItemDeleted),
    RealtimeServerEventConversationItemInputAudioTranscriptionCompleted(RealtimeServerEventConversationItemInputAudioTranscriptionCompleted),
    RealtimeServerEventConversationItemInputAudioTranscriptionDelta(RealtimeServerEventConversationItemInputAudioTranscriptionDelta),
    RealtimeServerEventConversationItemInputAudioTranscriptionFailed(RealtimeServerEventConversationItemInputAudioTranscriptionFailed),
    RealtimeServerEventConversationItemRetrieved(RealtimeServerEventConversationItemRetrieved),
    RealtimeServerEventConversationItemTruncated(RealtimeServerEventConversationItemTruncated),
    RealtimeServerEventError(RealtimeServerEventError),
    RealtimeServerEventInputAudioBufferCleared(RealtimeServerEventInputAudioBufferCleared),
    RealtimeServerEventInputAudioBufferCommitted(RealtimeServerEventInputAudioBufferCommitted),
    RealtimeServerEventInputAudioBufferDtmfEventReceived(RealtimeServerEventInputAudioBufferDtmfEventReceived),
    RealtimeServerEventInputAudioBufferSpeechStarted(RealtimeServerEventInputAudioBufferSpeechStarted),
    RealtimeServerEventInputAudioBufferSpeechStopped(RealtimeServerEventInputAudioBufferSpeechStopped),
    RealtimeServerEventRateLimitsUpdated(RealtimeServerEventRateLimitsUpdated),
    RealtimeServerEventResponseAudioDelta(RealtimeServerEventResponseAudioDelta),
    RealtimeServerEventResponseAudioDone(RealtimeServerEventResponseAudioDone),
    RealtimeServerEventResponseAudioTranscriptDelta(RealtimeServerEventResponseAudioTranscriptDelta),
    RealtimeServerEventResponseAudioTranscriptDone(RealtimeServerEventResponseAudioTranscriptDone),
    RealtimeServerEventResponseContentPartAdded(RealtimeServerEventResponseContentPartAdded),
    RealtimeServerEventResponseContentPartDone(RealtimeServerEventResponseContentPartDone),
    RealtimeServerEventResponseCreated(RealtimeServerEventResponseCreated),
    RealtimeServerEventResponseDone(RealtimeServerEventResponseDone),
    RealtimeServerEventResponseFunctionCallArgumentsDelta(RealtimeServerEventResponseFunctionCallArgumentsDelta),
    RealtimeServerEventResponseFunctionCallArgumentsDone(RealtimeServerEventResponseFunctionCallArgumentsDone),
    RealtimeServerEventResponseOutputItemAdded(RealtimeServerEventResponseOutputItemAdded),
    RealtimeServerEventResponseOutputItemDone(RealtimeServerEventResponseOutputItemDone),
    RealtimeServerEventResponseTextDelta(RealtimeServerEventResponseTextDelta),
    RealtimeServerEventResponseTextDone(RealtimeServerEventResponseTextDone),
    RealtimeServerEventSessionCreated(RealtimeServerEventSessionCreated),
    RealtimeServerEventSessionUpdated(RealtimeServerEventSessionUpdated),
    RealtimeServerEventOutputAudioBufferStarted(RealtimeServerEventOutputAudioBufferStarted),
    RealtimeServerEventOutputAudioBufferStopped(RealtimeServerEventOutputAudioBufferStopped),
    RealtimeServerEventOutputAudioBufferCleared(RealtimeServerEventOutputAudioBufferCleared),
    RealtimeServerEventConversationItemAdded(RealtimeServerEventConversationItemAdded),
    RealtimeServerEventConversationItemDone(RealtimeServerEventConversationItemDone),
    RealtimeServerEventInputAudioBufferTimeoutTriggered(RealtimeServerEventInputAudioBufferTimeoutTriggered),
    RealtimeServerEventConversationItemInputAudioTranscriptionSegment(RealtimeServerEventConversationItemInputAudioTranscriptionSegment),
    RealtimeServerEventMCPListToolsInProgress(RealtimeServerEventMCPListToolsInProgress),
    RealtimeServerEventMCPListToolsCompleted(RealtimeServerEventMCPListToolsCompleted),
    RealtimeServerEventMCPListToolsFailed(RealtimeServerEventMCPListToolsFailed),
    RealtimeServerEventResponseMCPCallArgumentsDelta(RealtimeServerEventResponseMCPCallArgumentsDelta),
    RealtimeServerEventResponseMCPCallArgumentsDone(RealtimeServerEventResponseMCPCallArgumentsDone),
    RealtimeServerEventResponseMCPCallInProgress(RealtimeServerEventResponseMCPCallInProgress),
    RealtimeServerEventResponseMCPCallCompleted(RealtimeServerEventResponseMCPCallCompleted),
    RealtimeServerEventResponseMCPCallFailed(RealtimeServerEventResponseMCPCallFailed),
}
