// Generated from OpenAPI spec. Do not edit by hand.
//! `RealtimeBetaResponse` DTO.

use serde::{Deserialize, Serialize};

use crate::models::{
    Metadata,
    RealtimeBetaResponseMaxOutputTokens,
    RealtimeBetaResponseStatusDetails,
    RealtimeBetaResponseUsage,
    RealtimeConversationItem,
    VoiceIdsShared,
};

/// The response resource.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RealtimeBetaResponse {
    /// The unique ID of the response.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// The object type, must be `realtime.response`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub object: Option<String>,
    /// The final status of the response (`completed`, `cancelled`, `failed`, or `incomplete`,
    /// `in_progress`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Additional details about the status.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status_details: Option<RealtimeBetaResponseStatusDetails>,
    /// The list of output items generated by the response.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output: Option<Vec<RealtimeConversationItem>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Metadata>,
    /// Usage statistics for the Response, this will correspond to billing. A Realtime API session will
    /// maintain a conversation context and append new Items to the Conversation, thus output from previous
    /// turns (text and audio tokens) will become the input for later turns.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub usage: Option<RealtimeBetaResponseUsage>,
    /// Which conversation the response is added to, determined by the `conversation` field in the
    /// `response.create` event. If `auto`, the response will be added to the default conversation and the
    /// value of `conversation_id` will be an id like `conv_1234`. If `none`, the response will not be added
    /// to any conversation and the value of `conversation_id` will be `null`. If responses are being
    /// triggered by server VAD, the response will be added to the default conversation, thus the
    /// `conversation_id` will be an id like `conv_1234`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conversation_id: Option<String>,
    /// The voice the model used to respond. Current voice options are `alloy`, `ash`, `ballad`, `coral`,
    /// `echo`, `sage`, `shimmer`, and `verse`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub voice: Option<VoiceIdsShared>,
    /// The set of modalities the model used to respond. If there are multiple modalities, the model will
    /// pick one, for example if `modalities` is `["text", "audio"]`, the model could be responding in
    /// either text or audio.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub modalities: Option<Vec<String>>,
    /// The format of output audio. Options are `pcm16`, `g711_ulaw`, or `g711_alaw`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output_audio_format: Option<String>,
    /// Sampling temperature for the model, limited to [0.6, 1.2]. Defaults to 0.8.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f64>,
    /// Maximum number of output tokens for a single assistant response, inclusive of tool calls, that was
    /// used in this response.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_output_tokens: Option<RealtimeBetaResponseMaxOutputTokens>,
}
