// Generated from OpenAPI spec. Do not edit by hand.
//! `Response` DTO.

use serde::{Deserialize, Serialize};

use crate::models::{
    Conversation2,
    Metadata,
    ModelIdsResponses,
    OutputItem,
    Prompt,
    Reasoning,
    ResponseError,
    ResponseIncompleteDetails,
    ResponseInstructions,
    ResponseTextParam,
    ResponseUsage,
    ServiceTier,
    ToolChoiceParam,
    ToolsArray,
};

/// The response object
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Response {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Metadata>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub top_logprobs: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub top_p: Option<f64>,
    /// This field is being replaced by `safety_identifier` and `prompt_cache_key`. Use `prompt_cache_key`
    /// instead to maintain caching optimizations. A stable identifier for your end-users. Used to boost
    /// cache hit rates by better bucketing similar requests and to help OpenAI detect and prevent abuse.
    /// [Learn more](/docs/guides/safety-best-practices#safety-identifiers).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub user: Option<String>,
    /// A stable identifier used to help detect users of your application that may be violating OpenAI's
    /// usage policies. The IDs should be a string that uniquely identifies each user, with a maximum length
    /// of 64 characters. We recommend hashing their username or email address, in order to avoid sending us
    /// any identifying information. [Learn more](/docs/guides/safety-best-practices#safety-identifiers).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub safety_identifier: Option<String>,
    /// Used by OpenAI to cache responses for similar requests to optimize your cache hit rates. Replaces
    /// the `user` field. [Learn more](/docs/guides/prompt-caching).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt_cache_key: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub service_tier: Option<ServiceTier>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt_cache_retention: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub previous_response_id: Option<String>,
    /// Model ID used to generate the response, like `gpt-4o` or `o3`. OpenAI offers a wide range of models
    /// with different capabilities, performance characteristics, and price points. Refer to the [model
    /// guide](/docs/models) to browse and compare available models.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<ModelIdsResponses>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reasoning: Option<Reasoning>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub background: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_tool_calls: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub text: Option<ResponseTextParam>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tools: Option<ToolsArray>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_choice: Option<ToolChoiceParam>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub prompt: Option<Prompt>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub truncation: Option<String>,
    /// Unique identifier for this Response.
    pub id: String,
    /// The object type of this resource - always set to `response`.
    pub object: String,
    /// The status of the response generation. One of `completed`, `failed`, `in_progress`, `cancelled`,
    /// `queued`, or `incomplete`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
    /// Unix timestamp (in seconds) of when this Response was created.
    pub created_at: f64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<ResponseError>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub incomplete_details: Option<ResponseIncompleteDetails>,
    /// An array of content items generated by the model. - The length and order of items in the `output`
    /// array is dependent on the model's response. - Rather than accessing the first item in the `output`
    /// array and assuming it's an `assistant` message with the content generated by the model, you might
    /// consider using the `output_text` property where supported in SDKs.
    pub output: Vec<OutputItem>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub instructions: Option<ResponseInstructions>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub output_text: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub usage: Option<ResponseUsage>,
    /// Whether to allow the model to run tool calls in parallel.
    pub parallel_tool_calls: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub conversation: Option<Conversation2>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub max_output_tokens: Option<i32>,
}
