[package]
name = "aio-adapter"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
aio-core = { path = "../aio-core" }
aio-engine = { path = "../aio-engine" }
aio-runtime = { path = "../aio-runtime" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
log.workspace = true

[lints]
workspace = true
