[package]
name = "az-drive-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
az-drive-agent.workspace = true
az-drive-core.workspace = true
az-drive-store.workspace = true
az-drive-webdav.workspace = true
clap = { version = "4.5.38", features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
shlex.workspace = true
tokio.workspace = true
toml_edit.workspace = true
urlencoding.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
