[package]
name = "az-curl"
description = "将 curl 命令字符串解析为结构化的 HTTP 请求表示，并支持直接执行。"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
az-derive-aliases.workspace = true
base64.workspace = true
regex.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
shlex.workspace = true
strum.workspace = true
thiserror.workspace = true

[lints]
workspace = true
