[package]
name = "az-excel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
automod.workspace = true
derive_more.workspace = true
quick-xml.workspace = true
zip.workspace = true

[lints]
workspace = true
