[package]
name = "az-drive-agent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
automod.workspace = true
az-drive-core.workspace = true
az-drive-store.workspace = true
chrono = { workspace = true, features = ["serde"] }
dirs.workspace = true
fs2 = "0.4"
ignore = "0.4"
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
strum.workspace = true
tokio.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
