[package]
name = "az-person-detection"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
description = "Local COCO SSD MobileNet person detection ONNX inference"
homepage.workspace = true
repository.workspace = true

[dependencies]
automod.workspace = true
az-algorithm-onnx.workspace = true
base64.workspace = true
half.workspace = true
image.workspace = true
imageproc.workspace = true
ndarray.workspace = true
ort = { workspace = true, features = ["half"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true

[lints]
workspace = true
