mod docker;
mod enable_all_sources;
mod env_scripts;
mod final_shell;
mod git;
mod graalvm;
mod homebrew;
mod idea;
mod jdk;
mod keji;
mod lazyvim;
mod macos;
mod node;
mod ohmyzsh;
mod package_manager;
mod pkg;
mod pnpm;
mod powershell;
mod powershell_env;
mod quark;
mod useful;
mod windows_optimizations;
mod zulu_jdk;

pub(crate) use docker::run as docker;
pub(crate) use enable_all_sources::run as enable_all_sources;
pub(crate) use env_scripts::run as env_scripts;
pub(crate) use final_shell::run as final_shell;
pub(crate) use git::run as git;
pub(crate) use graalvm::run as graalvm;
pub(crate) use homebrew::run as homebrew;
pub(crate) use idea::run as idea;
pub(crate) use jdk::run as jdk;
pub(crate) use keji::run as keji;
pub(crate) use lazyvim::run as lazyvim;
pub(crate) use macos::run as macos;
pub(crate) use node::run as node;
pub(crate) use ohmyzsh::run as ohmyzsh;
pub(crate) use package_manager::run as package_manager;
pub(crate) use pkg::run as pkg;
pub(crate) use pnpm::run as pnpm;
pub(crate) use powershell::run as powershell;
pub(crate) use powershell_env::run as powershell_env;
pub(crate) use quark::run as quark;
pub(crate) use zulu_jdk::run as zulu_jdk;
