[package]
name = "az-script-engine-rhai"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
automod.workspace = true
az-sandbox.workspace = true
az-script-engine.workspace = true
rhai = { version = "1", features = ["sync", "serde"] }
serde_json.workspace = true

[lints]
workspace = true
